### ISSUE TITLE
Is there any support for values containing new lines?

### ISSUE THREAD

**Issue by mariusneo** [inside-track/dtspec#28]
Is there a recipe on how to deal with new lines in the data tables?

"first line \n second line" is interpreted as "first line \\n second line" in Python.

Could you add a possibility to interpret multilines in the source/expected tables?

**Comment by gnilrets** [comment]
That's a good idea.  I know it wouldn't work right now in the tabular form.  But I think it would work in the `values` section of a factory definition using multiline yaml syntax (https://github.com/inside-track/dtspec/blob/master/tests/hello_world_multiple_cases.yml#L43).  So as long as you don't have to write tests that involve multiple records with different multi-line strings, you could use that.

**Comment by mariusneo** [comment]
Could you maybe paste a concrete example?

**Comment by mariusneo** [comment]
Thanks for the heads up. Good to know :)
