### ISSUE TITLE
Add datetime manipulation functions

### ISSUE THREAD

**Issue by findinpath** [inside-track/dtspec#31]
It would be very beneficial to have the ability to create on the fly values for a date column.

Say we have a table `raw_products`

In the test specification .yml file we have then:

```
           - source: raw_products
              table: |
                | export_time                           | file                                       | product_id         | product_name         |
                | -                                             | -                                          | -                        | -                               |
                | 2021-01-01 00:00:00+00:00  | products-2021-01-01.csv   | milk                   | Milk                          |
```

In some cases, specifying the `export_time` in a hardcoded fashion is enough to test all the logic from the model that is doing transformations on top of the `raw_products` table.

In some scenarios though, we may want to check some corner cases. Maybe the exported products are to be analyzed only up until yesterday, but not today.

In such a case it would be quite beneficial if via `dtspec` there could be specified `python` functions for generating on the fly the `export_time`.

**Comment by gnilrets** [comment]
That's a great point @findinpath.  dtspec doesn't directly support this.  However, you can get this functionality by parsing the yaml specs with Jinja before they are passed to dtspec.

I just recently did a quiet release of the [dtspec CLI](https://github.com/inside-track/dtspec#dtspec-cli-config) which helps integrate this tool with dbt (still need to write up some more docs).  That tool will compile dtspec yaml specs, and provides some convenience functions to the [Jinja parsing context](https://github.com/inside-track/dtspec/blob/master/dtspec/specs.py#L97) that does just this.  Some of the functions it provides include: `TODAY`, `YESTERDAY`, `TOMORROW`, and `relativedelta`.  They can be used like

           - source: raw_products
              table: |
                | export_time      | file                    | product_id | product_name |
                | -                | -                       | -          | -            |
                | {{ YESTERDAY }}  | products-2021-01-01.csv | milk       | Milk         |

**Comment by findinpath** [comment]
I've just found this ones: 

https://github.com/inside-track/dtspec/blob/master/dtspec/init/specs/main.yml
https://github.com/inside-track/dtspec/blob/master/dtspec/specs.py#L101



Hmm... this is a great addition.

I'd be very happy to have some way of granularly defining a date/datetime.

What I have in mind would be something similar to:

```
now.minus(DAYS, 5)
```

or 

```
now.minus(MINUTES, 10)
```

Do you have any idea if this could be done in dtspec without too much hassle?

**Comment by gnilrets** [comment]
Yeah, you can do that with `relativedelta`:
```
TODAY - relativedelta(days=5)
```

**Comment by findinpath** [comment]
Great. I'll try this out.
Thanks for the quick reply.

**Comment by gnilrets** [comment]
@findinpath - README updated which clarifies the Jinja context available in the CLI
